Blog/Models/Topics.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.Models
{
    public class Topics
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<BlogPost> Blogs { get; set; }
    }
}

Blog/Controllers/HomeController.cs
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.Threading.Tasks;
using System.Configuration;
using System.Net.Mail;

namespace Blog.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            //var max = db.Posts.OrderByDescending(p => p.Id).FirstOrDefault();
            //BlogPost blogPost = max;
            //if (blogPost == null)
            //{
            //    return HttpNotFound();
            //}
            ViewBag.ReturnUrl = Request.Url.LocalPath;
            return View(db.Posts.ToList());
        }

        //public ActionResult Topics()
        //{
        //    ViewBag.Message = "Feel free to browse through the blog posts by topic.";

        //    return View();
        //}

        public ActionResult About()
        {
            ViewBag.Message = "Here is my story. Short Version: I took the scenic route.";
            ViewBag.ReturnUrl = Request.Url.LocalPath;

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.ReturnUrl = Request.Url.LocalPath;
            ViewBag.StatusMessage = "";
            ViewBag.Message = "If you wish to contact me for some reason...";
            EmailModel model = new EmailModel();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var body = "<p>Email From: <bold>{0}</bold>({1})</p><p> Message:</p><p>{2}</p>";
                    var from = "MyBlog<kylecoder@gmail.com>";
                    model.Body = "This is a message from your blog site. The name and the email of the contacting person is above.";
                    var email = new MailMessage(from,
                         ConfigurationManager.AppSettings["emailto"])
                    {
                        Subject = "Blog Contact Email",
                        Body = String.Format(body, model.FromName, model.FromEmail, model.Body),
                        //Body = "test",
                        IsBodyHtml = true
                    };
                    var svc = new PersonalEmail();
                    await svc.SendAsync(email);


                    ViewBag.StatusMessage = "Success! Thanks for reaching out to me!";
                    //return RedirectToAction("Sent");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }
            }
            return View(model);
        }

        //public ActionResult Search(int? page)
        //{
        //    var Model = db.Posts.AsQueryable();
        //    int pageSize = 5; // display three blog posts at a time on this page
        //    int pageNumber = (page ?? 1);
        //    return View(Model.OrderByDescending(p => p.Created).ToPagedList(pageNumber, pageSize));
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        [HttpGet]
        public ActionResult Search(int? page, string search)
        {
            ViewBag.ReturnUrl = Request.Url.LocalPath;
            var blogResults = db.Posts.AsQueryable(); //Most efficient method
            ViewBag.search = search;
            if (!String.IsNullOrEmpty(search))
            {
                blogResults = db.Posts.Where(p => p.Body.Contains(search) || p.Title.Contains(search)
                                || p.Slug.Contains(search) || p.Comments.Any(c => c.Body.Contains(search)
                                || c.Author.DisplayName.Contains(search) || c.Author.FirstName.Contains(search)
                                || c.Author.LastName.Contains(search)) || p.Topics.Any(t=>t.Name.Contains(search)));

                //Slightly less efficient method
                //blogResults = db.Posts.Where(p => p.Title.Contains(search))
                //    .Union(db.Posts.Where(p => p.Slug.Contains(search)))
                //    .Union(db.Posts.Where(p => p.Body.Contains(search)))
                //    .Union(db.Posts.Where(p => p.Comments.Any(c => c.Body.Contains(search))))
                //    .Union(db.Posts.Where(p => p.Comments.Any(c => c.Author.DisplayName.Contains(search))))
                //    .Union(db.Posts.Where(p => p.Comments.Any(c => c.Author.LastName.Contains(search))))
                //    .Union(db.Posts.Where(p => p.Comments.Any(c => c.Author.FirstName.Contains(search))))
                //    .Union(db.Posts.Where(p => p.Comments.Any(c => c.Author.Email.Contains(search))))
                //    /*.Union(db.Posts.Where(p => p.Topics.Any(t => t.Name.Contains(search))))*/.AsQueryable();

                //Very inefficient method
                //var title = db.Posts.Where(p=>p.Title.Contains(search));
                //var blogResults = title.Union(db.Posts.Where(p => p.Slug.Contains(search)))
                //    .Union(db.Posts.Where(p => p.Body.Contains(search)))
                //var comment = db.Comments.Where(c => c.Body.Contains(search)).Union(db.Comments.Where(c => c.Author.;
                //foreach (var c in comment)
                //{
                //    blogResults.Union(db.Posts.Where(p => p.Id.Equals(c.BlogPostId)));
                //}
                //var topic = db.Topics.Where(c => c.Name.Contains(search));
                //foreach (var t in topic)
                //{
                //    foreach (var b in t.Blogs)
                //    {
                //        blogResults.Union(db.Posts.Where(p => p.Id.Equals(b.Id)));
                //    }
                //}

                //Session["search"] = blogResults;
                int pageSize = 3; // display three blog posts at a time on this page
                int pageNumber = (page ?? 1);
                //ViewBag.search = blogResults;
                return View(blogResults.OrderByDescending(p => p.Created).ToPagedList(pageNumber, pageSize));
                //List<BlogPost> resultsList = blogResults.ToList();
                //return View(resultsList);
            }
            //else if (page != null && String.IsNullOrEmpty(search))
            //{
            //    blogResults = Session["search"] as IQueryable<BlogPost>;

            //    int pageSize = 3; // display three blog posts at a time on this page
            //    int pageNumber = (page ?? 1);
            //    //ViewBag.search = blogResults;
            //    return View(blogResults.OrderByDescending(p => p.Created).ToPagedList(pageNumber, pageSize));
            //}
            else
            {
                //Session["search"] = null;
                int pageSize = 3; // display three blog posts at a time on this page
                int pageNumber = (page ?? 1);
                return View(blogResults.OrderByDescending(p => p.Created).ToPagedList(pageNumber, pageSize));
                //return RedirectToLocal(Request.Url.LocalPath);
            }

        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Blog/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    [RequireHttps]
    public class TopicsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Topics
        public ActionResult Index()
        {
            ViewBag.ReturnUrl = Request.Url.LocalPath;
            return View(db.Topics.ToList());
        }

        // GET: Topics/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.ReturnUrl = Request.Url.LocalPath;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topics topics = db.Topics.Find(id);
            if (topics == null)
            {
                return HttpNotFound();
            }
            return View(topics);
        }
        [Authorize]
        // GET: Topics/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Topics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Topics topics, string returnURL)
        {
            if (ModelState.IsValid)
            {
                db.Topics.Add(topics);
                db.SaveChanges();
                if(returnURL != null) {
                    return RedirectToLocal(returnURL);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }

            return View(topics);
        }

        // GET: Topics/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topics topics = db.Topics.Find(id);
            if (topics == null)
            {
                return HttpNotFound();
            }
            return View(topics);
        }

        // POST: Topics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Topics topics)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topics).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topics);
        }

        // GET: Topics/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topics topics = db.Topics.Find(id);
            if (topics == null)
            {
                return HttpNotFound();
            }
            return View(topics);
        }

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topics topics = db.Topics.Find(id);
            db.Topics.Remove(topics);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="container-fluid backdrop-gradient">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>About The Author</h2>
            <h3>@ViewBag.Message</h3>
            <p>Here's the long version:</p>
            <p>I am a full stack software developer in the making. Throughout my life, I have always loved technology and have been drawn to computers. I even took coding lessons when I was 11 years old. However, I stepped away from coding as a teenager and, save one course in High School, did not encounter it again until graduate school.</p>
            <p>My journey through college took me first to a pre-pharmacy track where I spent 3 years studying alongside the future doctors of the world. Although I kept step with them, I realized that they were far more passionate about the topics than I was. So, I changed majors to the social science field of Family Studies.</p>
            <p>I graduated with a degree in Family Studies and went to graduate school in pursuit of a Ph.D. My training in graduate school centered around statistical analysis. My advisor was a demographer and she specialized in analyzing large datasets. The statistics software I used every day was code-based, meaning, I had to code in order to use the software to statistically analyze the data. I soon found that I enjoyed writing code more than I enjoyed statistics.</p>
            <p>Thus, I made another change after completing the requirements for a master's degree. I am now pursuing my love of coding and I hope that I get to build software and solve complex puzzles the rest of my career!</p>
        </div>
    </div>
</div>

Blog/Views/Home/Contact.cshtml
@model Blog.Models.EmailModel
@{
    ViewBag.Title = "Contact";
}

<div class="container-fluid backdrop-gradient">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-1">
            <h2>@ViewBag.Title</h2>
            <h3>@ViewBag.Message</h3>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <h4>Enter your name and email below and I will get in touch with you</h4>
                <hr />
                <p style="font-weight:bold; color:lime;">@ViewBag.StatusMessage</p>
                @Html.ValidationSummary("",new { @class = "text-danger"})
                <div class="form-group">
                    @Html.LabelFor(m => m.FromName, new { @class = "col-md-2 control-label" }) 
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.FromName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.FromName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.FromEmail, new { @class = "col-md-2 control-label" }) 
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control", placeholder = "example@email.com" })
                        @Html.ValidationMessageFor(m => m.FromEmail)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn links-btn" value="Send" />
                    </div>
                </div>
            }

            @*<p>I'd be happy to receive an email from you if you feel that you have something you wish to say to me. I'm always interested in fan-mail so don't hold back if you're a fan.</p>
            <p>If you're interested in learning more about who I am and what I'm about, I suggest you check out <a href="https://kbartholomew-portfolio.azurewebsites.net" class="links"><u>my portfolio</u></a>.</p>

            <address>
                <strong>Email:</strong>   <a href="mailto:kyle.r.bartholomew@gmail.com" class="links">kyle.r.bartholomew@gmail.com</a><br />
            </address>*@
        </div>
    </div>
</div>

Blog/Views/Home/Index.cshtml
@model IEnumerable<Blog.Models.BlogPost>

@{
    ViewBag.Title = "Home Page";
}
@*<!DOCTYPE html>
    <html lang="en">*@
@*<head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Full Slider - Start Bootstrap Template</title>

        <!-- Bootstrap Core CSS -->
        <link href="~/Content/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="~/Content/full-slider.css" rel="stylesheet">

        <link href="~/Content/flickity.css" rel="stylesheet" media="screen">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>*@
@*<body>*@
<!-- Navigation -->
@*<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>*@
<!-- Full Page Image Background Carousel Header -->
<!--<header id="myCarousel" class="carousel slide">
     Indicators
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>-->
<!-- Wrapper for Slides -->
<div class="carousel container-fluid" data-flickity='{ "freeScroll": true, "contain": true, "pageDots": false, "autoPlay": true }'>
    <div class="carousel-cell fill">
        <!-- Set the first background image using inline CSS below. -->
        <div class="jumbotron">
            <h1 style="font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif">Kyle's Coder Blog</h1>
            <p class="lead">Enjoy candid documentation of my journey to becoming a software developer.</p>
        </div>
    </div>
    @{
    int num = 0;
    foreach (var item in Model.Reverse())
            {
        <div class="carousel-cell fill">
            <!-- Set the second background image using inline CSS below. -->
            <div class="row text-center">
                <h1>@Html.ActionLink(item.Title, "Details", "BlogPosts", new { Slug = item.Slug }, new { @class = "links", style = "font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif" })</h1>
            </div>
            <div class="row text-left">
                <div class="col-lg-8 col-lg-offset-2">
                    <p align="right" id="created_date_@num"></p>
                </div>
            </div>
            @if (item.Topics != null)
                {
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <p align="right" style="font-size:1em;">Topics</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2 pull-right">
                    </div>
                    <div class="col-lg-4 pull-right">
                        <p style="font-size:.75em;" align="right">
                            @foreach (var topic in item.Topics)
                    {
                        if (topic != item.Topics.Last())
                        {
                                    @Html.ActionLink(topic.Name, "Details", "Topics", new { id = topic.Id }, new { @class = "links" })<span>, </span>
                                }
                                else
                                {
                                    @Html.ActionLink(topic.Name, "Details", "Topics", new { id = topic.Id }, new { @class = "links" })
                                }
                            }
                        </p>
                    </div>
                </div>
            }
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <hr />
                </div>
            </div>
            <div class="row text-left">
                @if (item.MediaURL != null)
                {
                    <div class="col-lg-8 col-lg-offset-2">
                        <img class="img-responsive img-rounded pull-left" style="width:50%; margin-right:1em; margin-bottom:0.5em;" src="@item.MediaURL" />
                        @if (item.Body.Length > 500)
                        {
                            string truncBody = item.Body.Substring(0, 500) + "...</p>";

                            @Html.Raw(truncBody)
                        }
                        else
                        {
                            @Html.Raw(item.Body)
                        }
                    </div>

                }
                else
                {
                    if (item.Body.Length > 750)
                    {
                        string truncBody = item.Body.Substring(0, 750) + "...</p>";

                        <div class="col-lg-8 col-lg-offset-2">
                            @Html.Raw(truncBody)
                        </div>
                    }
                    else
                    {
                        <div class="col-lg-8 col-lg-offset-2">
                            @Html.Raw(item.Body)
                        </div>
                    }
                }
            </div>

            <!--<div class="carousel-caption">
                <h2>Caption 2</h2>
            </div>-->
        </div>
            num++;
        }
        }
</div>
<!-- Controls -->
<!--<a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
</a>
<a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
</a>-->
<!--</header>-->
<!-- Page Content -->
@*<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <h1>Full Slider by Start Bootstrap</h1>
            <p>The background images for the slider are set directly in the HTML using inline CSS. The rest of the styles for this template are contained within the <code>full-slider.css</code>file.</p>
        </div>
    </div>

    <hr>

     Footer
    @*<footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
         /.row
    </footer>*@
@*</div>*@
<!-- /.container -->
@*<!-- jQuery -->
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <!-- Flickity -->
    <script src="~/Scripts/flickity.pkgd.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>*@
<!-- Script to Activate the Carousel -->
@*<script>
    //$('.carousel').carousel({
    //    interval: 5000 //changes the speed
    //})
    </script>*@
@*</body>

    </html>*@
@section scripts{
    <script type="text/javascript">
        function fixDate(count, created) {
            var time1 = getUserTime(created);
            $("#created_date_" + count).html("Created: " + time1);

        }

        @{
                int count = 0;
                foreach (var blog in Model.Reverse())
                {
                    @:fixDate(@count,'@blog.Created.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")');
                            count++;
                }
            }

    </script>
    }

Blog/Views/Home/Topics.cshtml
@{
    ViewBag.Title = "Topics";
}

<h2>@ViewBag.Title</h2>

<h3>@ViewBag.Message</h3>