Blog/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Models
{
    public class BlogPost
    {
        public BlogPost() //This is a constructor
        {
            this.Comments = new HashSet<Comments>();
            this.Topics = new HashSet<Topics>();
        }

        public int Id { get; set; }
        public string Author { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Modified { get; set; }
        public string ModifiedNote { get; set; }
        public bool Private { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        [AllowHtml]
        public string Body { get; set; }
        public string MediaURL { get; set; } //What if I want multiple?
        public virtual ICollection<Topics> Topics { get; set; }
        public bool Published { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}

Blog/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace Blog.Controllers
{
    [RequireHttps]
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        public ActionResult Index(int? page)
        {
            ViewBag.ReturnUrl = Request.Url.LocalPath;
            //BlogVM BlogPost = new BlogVM();
            //BlogPost.BlogPost = db.Posts.ToList();
            //if (db.Topics.Count() == 0)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //else
            //{
            //    BlogPost.Topics = db.Topics.ToList();
            //};
            //BlogPost.Comments = db.Comments.ToList();
            //return View(BlogPost);
            int pageSize = 3; // display three blog posts at a time on this page
            int pageNumber = (page ?? 1);
            return View(db.Posts.AsQueryable().OrderByDescending(p => p.Created).ToPagedList(pageNumber, pageSize));
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(string Slug)
        {
            ViewBag.ReturnUrl = Request.Url.AbsolutePath; //Request.Url.AbsolutePath is the URL that is fed to the controller from whatever was clicked it to send it here (a.k.a. the URL of the location the controller is directing you to.) 
            if (Slug == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(b => b.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }
        [Authorize(Roles = "Admin")]
        // GET: BlogPosts/Create
        public ActionResult Create()
        {
            ViewBag.ReturnUrl = Request.Url.LocalPath;
            ViewBag.Topics = new MultiSelectList(db.Topics, "Id", "Name");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Modified,ModifiedNote,Private,Title,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image, List<string> Topics)
        {
            if (ModelState.IsValid)
            {
                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }

                var user = db.Users.Find(User.Identity.GetUserId());
                blogPost.Author = user.Id;
                if (Topics != null)
                {
                    var TopicsList = new List<Topics>();
                    foreach (var item in Topics)
                    {
                        int intItem = Convert.ToInt32(item);
                        var TopicNum = db.Topics.Find(intItem);
                        TopicsList.Add(TopicNum);
                    }
                    blogPost.Topics = TopicsList;
                }
                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }
                if (db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }

                blogPost.Slug = Slug;
                blogPost.Created = DateTimeOffset.Now;

                db.Posts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Topics = new MultiSelectList(db.Topics, "Id", "Name");
            return View(blogPost);
        }

        [Authorize(Roles = "Admin")]
        // GET: BlogPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            var selectedBlogIds = new List<int>();
            foreach (var item in blogPost.Topics)
            {
                selectedBlogIds.Add(item.Id);
            }

            ViewBag.ReturnUrl = Request.Url.LocalPath;
            ViewBag.Topics = new MultiSelectList(db.Topics, "Id", "Name", selectedBlogIds);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Created,Modified,ModifiedNote,Private,Title,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image, List<string> Topics)
        {
            var blog = db.Posts.Find(blogPost.Id);
            if (ModelState.IsValid)
            {
                //I had to do this because for some reason it quit recognizing blogPost as being in the database.
                blog.Title = blogPost.Title;
                blog.Body = blogPost.Body;
                blog.ModifiedNote = blogPost.ModifiedNote;
                blog.Private = blogPost.Private;
                blog.Published = blogPost.Published;

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blog.MediaURL = "/Uploads/" + fileName;
                }

                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }
                //if (db.Posts.Any(p => p.Slug == Slug))
                //{
                //    ModelState.AddModelError("Title", "The title must be unique");
                //    return View(blogPost);
                //}

                blog.Topics.Clear();
                //foreach (var item in blog.Topics)
                //{
                //    blog.Topics.Remove(item);

                //    //db.Entry(blog).Property("Topics").IsModified = true;
                //} This way is wrong. Use .Clear() instead.
                //Once all the topics have been cleared out, you should add the new ones in.
                if (Topics != null)
                {
                    foreach (var item in Topics)
                    {
                        int intItem = Convert.ToInt32(item);
                        var TopicNum = db.Topics.Find(intItem);
                        blog.Topics.Add(TopicNum);
                    }
                }
                blog.Slug = Slug;
                blog.Modified = DateTimeOffset.Now;
                db.Entry(blog).State = EntityState.Modified; //EntityState.Modified says that if anything has changed, you updated all values in the table for this case.
                db.SaveChanges();
                return RedirectToAction("Details", "BlogPosts", new { Slug = Slug });
            }
            return View(blog);
        }

        [Authorize(Roles = "Admin")]
        // GET: BlogPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.Posts.Find(id);
            db.Posts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using Microsoft.AspNet.Identity;

namespace Blog.Controllers
{
    [RequireHttps]
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Author);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = db.Comments.Find(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.BlogPostId = new SelectList(db.Posts, "Id", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "BlogPostId,Body,ProfilePicURL,Private")] Comments comments)
        {
            if (ModelState.IsValid)
            {
                var slug = db.Posts.FirstOrDefault(x => x.Id == comments.BlogPostId).Slug;
                var user = db.Users.Find(User.Identity.GetUserId());
                comments.AuthorId = user.Id;
                comments.Created = DateTimeOffset.Now;
                db.Comments.Add(comments);
                db.SaveChanges();
                return RedirectToAction("Details", "BlogPosts", new { Slug = slug });
            }

            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", comments.AuthorId);
            ViewBag.BlogPostId = new SelectList(db.Posts, "Id", "Title", comments.BlogPostId);
            return View(comments);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = db.Comments.Find(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            var slug = db.Posts.FirstOrDefault(x => x.Id == comments.BlogPostId).Slug;
            ViewBag.Slug = slug;
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", comments.AuthorId);
            return View(comments);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Modified,ModifiedNote,Body,Private,Id")] Comments comments)
        {
            if (ModelState.IsValid)
            {
                var modCom = db.Comments.Find(comments.Id);
                modCom.Body = comments.Body;
                var slug = db.Posts.FirstOrDefault(x => x.Id == modCom.BlogPostId).Slug;
                modCom.Modified = DateTimeOffset.Now;
                db.Entry(modCom).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "BlogPosts", new { Slug = slug });
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", comments.AuthorId);
            return View(comments);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = db.Comments.Find(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            var slug = db.Posts.FirstOrDefault(x => x.Id == comments.BlogPostId).Slug;
            ViewBag.Slug = slug;
            return View(comments);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comments comments = db.Comments.Find(id);
            var slug = db.Posts.FirstOrDefault(x => x.Id == comments.BlogPostId).Slug;
            db.Comments.Remove(comments);
            db.SaveChanges();
            return RedirectToAction("Details","BlogPosts",new {Slug = slug });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Views/BlogPosts/Create.cshtml
@model Blog.Models.BlogPost

@{
    ViewBag.Title = "Create";
}
<div class="container-fluid backdrop-gradient">
    <h2>Create</h2>

    @using (Html.BeginForm("Create", "BlogPosts", FormMethod.Post, new { enctype = "Multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>BlogPost</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Upload Image", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.MediaURL, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input name="image" type="file" class="form-control" id="fileUpload" />
                    @Html.ValidationMessageFor(model => model.MediaURL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Private, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Private)
                        @Html.ValidationMessageFor(model => model.Private, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Published)
                        @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Topics, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.ListBox("Topics", null)
                    @Html.ValidationMessageFor(model => model.Topics, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                    <button href="#create-topic-modal" type="button" data-toggle="modal" class="btn links-btn">Create New Topic</button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn links-btn" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn links-btn" })
    </div>
</div>





@*Topics Modal*@
<div class="modal fade" id="create-topic-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="container modal-dialog">
        <div class="row">
            <div class="col-lg-1 pull-right">
                <button type="button" class="close" style="color:#cccccc;" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <span style="color:red; font-weight:bold">Caution! If you add a new topic from here, you will lose your work.</span>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-lg-offset-1">
                @using (Html.BeginForm("Create", "Topics", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label for="Name">New Topic:</label>
                        <input type="text" name="Name" class="form-control form-gradient" />
                    </div>
                    <div class="form-group col-lg-6 col-lg-offset-1">
                        <button type="submit" class="btn links-btn">Submit</button>
                    </div>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <button type="button" class="btn links-btn" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
            </div>
        </div>
    </div>
</div>


        @section scripts{
            <script src="~/Scripts/tinymce/tinymce.min.js"></script>
            <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
            <script type="text/javascript">
                $(function () {
                    tinymce.init({
                        selector: '#Body'
                    });
                });
            </script>

        }

Blog/Views/BlogPosts/Details.cshtml
@model Blog.Models.BlogPost

@{
    ViewBag.Title = "Details";
}
<div class="container-fluid backdrop-gradient">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-center">
            <h2 style="font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif">@Html.DisplayFor(model => model.Title)</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <p align="right" style="font-size:0.75em;" id="post_created"></p>
        </div>
    </div>
    @if (Model.Topics != null)
    {
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <p align="right" style="font-size:1em;">Topics</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2 pull-right">
            </div>
            <div class="col-lg-4 pull-right">
                <p style="font-size:.75em;" align="right">
                    @foreach (var topic in Model.Topics)
                    {
                        if (topic != Model.Topics.Last())
                        {
                            @Html.ActionLink(topic.Name, "Details", "Topics", new { id = topic.Id }, new { @class = "links" })<span>, </span>
                        }
                        else
                        {
                            @Html.ActionLink(topic.Name, "Details", "Topics", new { id = topic.Id }, new { @class = "links" })
                        }
                    }
                </p>
            </div>
        </div>
    }
    <hr />



    <div class="row">
        <div class="col-lg-8 col-lg-offset-2" style="font-size:1.25em; margin-bottom:2em;">
            @if (Model.MediaURL != null)
            {
                <img class="img-responsive img-rounded pull-left img-start blog-img" src="@Model.MediaURL" alt="" />
            }
            @Html.Raw(Model.Body)
        </div>
    </div>
    @if (Request.IsAuthenticated)
    {
        <div class="row" style="margin-top:1.5em">
            <div class="col-lg-2 col-lg-offset-2">
                <h5>Add New Comment:</h5>
            </div>
            <div class="col-lg-6" style="padding-top:1em">
                @using (Html.BeginForm("Create", "Comments", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    //Id,AuthorId,BlogPostId,Created,Modified,ModifiedNote,Body,ProfilePicURL,Private
                    <input type="hidden" name="BlogPostId" value="@Model.Id" />
                    <div class="form-group">
                        <label></label>
                        <div class="col-md-10">
                            <textarea name="Body" class="form-control form-gradient" required></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <div class="checkbox">
                                <label><input type="checkbox" name="Private" value="TRUE" /> Private</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn links-btn">Submit</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-lg-2 col-lg-offset-2">
                Add New Comment:
            </div>
            <div class="col-lg-6">
                @Html.ActionLink("Log in to leave a comment.", "Login", "Account", new { returnUrl = ViewBag.ReturnUrl }, new { @class = "links-btn btn" }) @*The returnUrl piece is called the routeValue. This value allows you to create a redirect path to come back to it, or send you somewhere else afterwards.*@
            </div>
        </div>
    }
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-left">
            <button class="btn links-btn" style="font-size:1.25em" id="comments-title">Comments</button>
        </div>
    </div>
    <div id="comments-list" style="display:none">
        @{ 
        int num = 0;
        foreach (var item in Model.Comments.Reverse())
        {
            <div class="row comment-gradient">
                <div class="col-lg-8 col-lg-offset-2" style="border-top:solid; border-width:1px; padding-top:1em">
                    <p align="left">@Html.Raw(item.Body)</p>
                    <p align="right">@Html.Raw(item.Author.DisplayName)</p>
                    <p align="right" id="comment_created_@num"></p>
                </div>
                @if (User.IsInRole("Moderator") || User.IsInRole("Admin"))
                {
                    <div class="col-lg-2">
                        @Html.ActionLink("Edit", "Edit", "Comments", new { id = item.Id }, new { @class = "links-btn btn" })
                        @Html.ActionLink("Delete", "Delete", "Comments", new { id = item.Id }, new { @class = "links-btn btn" })
                    </div>
                }
            </div>
            num++;
        }
        }
    </div>
</div>

@*<div>
    <h4>BlogPost</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedNote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedNote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Private)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Private)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Published)
        </dd>

        <dt>
            Comments:
        </dt>
        @foreach (var item in Model.Comments)
        {
            <dd>
                @Html.Raw(item.Body)
            </dd>
        }
        @if (Request.IsAuthenticated)
        {
        <dt>
            Add New Comment:
        </dt>
        <dd>
            @using (Html.BeginForm("Create", "Comments", FormMethod.Post,new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                //Id,AuthorId,BlogPostId,Created,Modified,ModifiedNote,Body,ProfilePicURL,Private
                <input type="hidden" name="BlogPostId" value="@Model.Id" />
                <div class="form-group">
                    <label></label>
                    <div class="col-md-10">
                        <input type="text" name="Body" class="form-control" required id="comment-body"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <div class="checkbox">
                            <label>Private<input type="checkbox" name="Private" /></label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            }
            </dd>
        } else
        {
            <dt>
                Add New Comment:
            </dt>
            <dd>
                @Html.ActionLink("Log in to leave a comment.", "Login", "Account", new { returnUrl = ViewBag.ReturnUrl }, new { @class = "links" }) @*The returnUrl piece is called the routeValue. This value allows you to create a redirect path to come back to it, or send you somewhere else afterwards.*@
@*</dd>
            }
        </dl>
    </div>*@
<p>
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "links-btn btn" })
    }
    @Html.ActionLink("Back to List", "Index", null, new { @class = "links-btn btn" })
</p>

@section scripts{
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script type="text/javascript">
        function fixDate(count, created) {
            var time = getUserTime(created);
            $("#comment_created_" + count).html("Created: " + time);
        }
        $(document).ready(function(){
            var blogDate = getUserTime('@Model.Created.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")');
            $("#post_created").html("Created: " + blogDate);

        @{
            int count = 0;
            foreach (var comment in Model.Comments.Reverse())
            {
                @:fixDate(@count,'@comment.Created.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")');
                count++;
            }
        }
            $(function () {
                tinymce.init({
                    selector: '#comment-body'
                });
            });
        })
    </script>

}